version: "3.9"

services:
  api:
    build: .
    env_file: .env
    depends_on:
      - es
      - redis
      - postgres
    expose:            # изменено — порт наружу больше не нужен
      - "8000"

  nginx:               # добавлено ─ nginx‑прокси
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api

  es:
    image: elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PG_DB:-movies_db}
      POSTGRES_USER: ${PG_USER:-app}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-secret}
    expose:
      - "5432"
    #ports:
    #  - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
